### ISSUE TITLE
How can I make the fonts smaller? I put it on my right side of screen, takes up half the page.

### ISSUE THREAD

**Issue by djloot** [cure/MMM-NextEvent#1]

**Comment by cure** [comment]
Hi @djloot! You could edit _MMM-NextEvent.css_, for example like this:

```
.green {
  color: #0f0;
  font-size: small;
}

.yellow {
  color: #ff0;
  font-size: small;
}

.red {
  color: #f00;  
  font-size: small;
}
```

You can also use a fixed pixel size (e.g. _15px_ ) or a relative percentage size (e.g. _50%_). Does this help?

**Comment by cure** [comment]
I'm going to assume my response was enough to answer your question, feel free to re-open if not. Thanks!
